import pandas as pd
import matplotlib.pyplot as plt

file_path = "data/processed_student_performance.csv"
df = pd.read_csv(file_path)

print("Starting to generate plots...")
plt.bar(df["Student"], df["Final_Score"], color="skyblue")
plt.title("Final Scores by Student")
plt.xlabel("Student Name")
plt.ylabel("Final Score")
plt.xticks(rotation=45)
plt.tight_layout()  
plt.savefig("plots/final_scores.png")
plt.close()
print("- Saved: final_scores.png")
plt.scatter(df["Hours_Studied"], df["Final_Score"], color="green")
plt.title("Hours Studied vs Final Score")
plt.xlabel("Hours Studied")
plt.ylabel("Final Score")
plt.grid(True)  
plt.savefig("plots/study_vs_score.png")
plt.close()
print("- Saved: study_vs_score.png")
plt.hist(df["Final_Score"], bins=5, color="orange", edgecolor="black")
plt.title("Distribution of Final Scores")
plt.xlabel("Final Score Range")
plt.ylabel("Number of Students")
plt.savefig("plots/score_distribution.png")
plt.close()
print("- Saved: score_distribution.png")
plt.scatter(df["Attendance"], df["Improvement"], color="purple")
plt.title("Attendance vs Grade Improvement")
plt.xlabel("Attendance (%)")
plt.ylabel("Improvement (Points)")
plt.grid(True)
plt.savefig("plots/custom_plot.png")
plt.close()
print("- Saved")

print("\n done  check  folder ")